export const carousel: string[] = [
  '../../../assets/swiper-images/epping-01.webp',
  '../../../assets/swiper-images/epping-09.webp',
  '../../../assets/swiper-images/versace-bathroom.webp',
  '../../../assets/swiper-images/epping-10.webp',
  '../../../assets/swiper-images/epping-11.webp',
  '../../../assets/swiper-images/cornwall-03.webp',
  '../../../assets/swiper-images/epping-13.webp',
  '../../../assets/swiper-images/green-dragon-03.webp',
  '../../../assets/swiper-images/green-dragon-06.webp',
];
export const carouselMobile: string[] = [
  '../../../assets/swiper-images/mobile/epping-01.webp',
  '../../../assets/swiper-images/mobile/epping-09.webp',
  '../../../assets/swiper-images/mobile/versace-bathroom.webp',
  '../../../assets/swiper-images/mobile/epping-10.webp',
  '../../../assets/swiper-images/mobile/epping-11.webp',
  '../../../assets/swiper-images/mobile/cornwall-03.webp',
  '../../../assets/swiper-images/mobile/epping-13.webp',
  '../../../assets/swiper-images/mobile/green-dragon-03.webp',
  '../../../assets/swiper-images/mobile/green-dragon-06.webp',
];

export const projectOneImages: string[] = [
  '../../../assets/gallery/epping-project/epping-01.webp',
  '../../../assets/gallery/epping-project/epping-02.webp',
  '../../../assets/gallery/epping-project/epping-03.webp',
  '../../../assets/gallery/epping-project/epping-04.webp',
  '../../../assets/gallery/epping-project/epping-05.webp',
  '../../../assets/gallery/epping-project/epping-06.webp',
  '../../../assets/gallery/epping-project/epping-07.webp',
  '../../../assets/gallery/epping-project/epping-08.webp',
  '../../../assets/gallery/epping-project/epping-09.webp',
  '../../../assets/gallery/epping-project/epping-10.webp',
  '../../../assets/gallery/epping-project/epping-11.webp',
  '../../../assets/gallery/epping-project/epping-12.webp',
  '../../../assets/gallery/epping-project/epping-13.webp',
  '../../../assets/gallery/epping-project/epping-14.webp',
  '../../../assets/gallery/epping-project/epping-15.webp',
  '../../../assets/gallery/epping-project/epping-16.webp',
  '../../../assets/gallery/epping-project/epping-17.webp',
  '../../../assets/gallery/epping-project/epping-18.webp',
  '../../../assets/gallery/epping-project/epping-19.webp',
  '../../../assets/gallery/epping-project/epping-20.webp',
  '../../../assets/gallery/epping-project/epping-21.webp',
  '../../../assets/gallery/epping-project/epping-22.webp',
  '../../../assets/gallery/epping-project/epping-23.webp',
  '../../../assets/gallery/epping-project/epping-24.webp',
  '../../../assets/gallery/epping-project/epping-25.webp',
];

export const projectTwoImages: string[] = [
  '../../../assets/gallery/green-dragon/green-dragon-01.webp',
  '../../../assets/gallery/green-dragon/green-dragon-02.webp',
  '../../../assets/gallery/green-dragon/green-dragon-03.webp',
  '../../../assets/gallery/green-dragon/green-dragon-04.webp',
  '../../../assets/gallery/green-dragon/green-dragon-05.webp',
  '../../../assets/gallery/green-dragon/green-dragon-06.webp',
  '../../../assets/gallery/green-dragon/green-dragon-07.webp',
  '../../../assets/gallery/green-dragon/green-dragon-09.webp',
  '../../../assets/gallery/green-dragon/green-dragon-10.webp',
  '../../../assets/gallery/green-dragon/green-dragon-12.webp',
  '../../../assets/gallery/green-dragon/green-dragon-15.webp',
  '../../../assets/gallery/green-dragon/green-dragon-11.webp',
  '../../../assets/gallery/green-dragon/green-dragon-08.webp',
  '../../../assets/gallery/green-dragon/green-dragon-14.webp',
  '../../../assets/gallery/green-dragon/green-dragon-13.webp',
  '../../../assets/gallery/green-dragon/green-dragon-16.webp',
  '../../../assets/gallery/green-dragon/green-dragon-17.webp',
  '../../../assets/gallery/green-dragon/green-dragon-18.webp',
  '../../../assets/gallery/green-dragon/green-dragon-19.webp',
  '../../../assets/gallery/green-dragon/green-dragon-21.webp',
];
export const projectThreeImages: string[] = [
  '../../../assets/gallery/cornwall/cornwall-02.webp',
  '../../../assets/gallery/cornwall/cornwall-03.webp',
  '../../../assets/gallery/cornwall/cornwall-04.webp',
  '../../../assets/gallery/cornwall/cornwall-05.webp',
  '../../../assets/gallery/cornwall/cornwall-06.webp',
  '../../../assets/gallery/cornwall/cornwall-07.webp',
  '../../../assets/gallery/cornwall/cornwall-08.webp',
  '../../../assets/gallery/cornwall/cornwall-09.webp',
  '../../../assets/gallery/cornwall/cornwall-10.webp',
  '../../../assets/gallery/cornwall/cornwall-11.webp',
  '../../../assets/gallery/cornwall/cornwall-01.webp',
  '../../../assets/gallery/cornwall/cornwall-12.webp',
];
export const projectFourImages: string[] = [
  '../../../assets/gallery/dany&dean/dany&dean-01.webp',
  '../../../assets/gallery/dany&dean/dany&dean-02.webp',
  '../../../assets/gallery/dany&dean/dany&dean-03.webp',
  '../../../assets/gallery/dany&dean/dany&dean-04.webp',
  '../../../assets/gallery/dany&dean/dany&dean-05.webp',
  '../../../assets/gallery/dany&dean/dany&dean-06.webp',
  '../../../assets/gallery/dany&dean/dany&dean-08.webp',
  '../../../assets/gallery/dany&dean/dany&dean-09.webp',
];
export const projectFiveImages: string[] = [
  '../../../assets/gallery/amurg-restaurant/amurg-01.webp',
  '../../../assets/gallery/amurg-restaurant/amurg-02.webp',
  '../../../assets/gallery/amurg-restaurant/amurg-03.webp',
  '../../../assets/gallery/amurg-restaurant/amurg-04.webp',
  '../../../assets/gallery/amurg-restaurant/amurg-05.webp',
  '../../../assets/gallery/amurg-restaurant/amurg-06.webp',
];
export const projectSixImages: string[] = [
  '../../../assets/gallery/pancroft/pancroft-01.webp',
  '../../../assets/gallery/pancroft/pancroft-02.webp',
  '../../../assets/gallery/pancroft/pancroft-10.webp',
  '../../../assets/gallery/pancroft/pancroft-03.webp',
  '../../../assets/gallery/pancroft/pancroft-04.webp',
  '../../../assets/gallery/pancroft/pancroft-05.webp',
  '../../../assets/gallery/pancroft/pancroft-06.webp',
  '../../../assets/gallery/pancroft/pancroft-07.webp',
  '../../../assets/gallery/pancroft/pancroft-08.webp',
  '../../../assets/gallery/pancroft/pancroft-09.webp',
];
export const projectSevenImages: string[] = [
  '../../../assets/gallery/prince-george/prince-george-02.webp',
  '../../../assets/gallery/prince-george/prince-george-01.webp',
  '../../../assets/gallery/prince-george/prince-george-03.webp',
  '../../../assets/gallery/prince-george/prince-george-10.webp',
  '../../../assets/gallery/prince-george/prince-george-04.webp',
  '../../../assets/gallery/prince-george/prince-george-05.webp',
  '../../../assets/gallery/prince-george/prince-george-07.webp',
  '../../../assets/gallery/prince-george/prince-george-08.webp',
  '../../../assets/gallery/prince-george/prince-george-06.webp',
  '../../../assets/gallery/prince-george/prince-george-09.webp',
  '../../../assets/gallery/prince-george/prince-george-11.webp',
];
export const projectEightImages: string[] = [
  '../../../assets/gallery/tauton/tauton-01.webp',
  '../../../assets/gallery/tauton/tauton-02.webp',
  '../../../assets/gallery/tauton/tauton-03.webp',
  '../../../assets/gallery/tauton/tauton-04.webp',
  '../../../assets/gallery/tauton/tauton-05.webp',
  '../../../assets/gallery/tauton/tauton-06.webp',
  '../../../assets/gallery/tauton/tauton-07.webp',
  '../../../assets/gallery/tauton/tauton-08.webp',
  '../../../assets/gallery/tauton/tauton-09.webp',
  '../../../assets/gallery/tauton/tauton-10.webp',
];

export const projectNineImages: string[] = [
  '../../../assets/gallery/versace-bathroom/versace-bathroom.webp',
  '../../../assets/gallery/versace-bathroom/versace-bathroom-02.webp',

  '../../../assets/gallery/versace-bathroom/versace-video.webm',
];
